### ISSUE TITLE
手动组网执行到给Org1安装sacc  fabricInstall payment.fabric.sacc Org1 contracts/chaincode/sacc 1.0 GO_LANG报错

### ISSUE THREAD

**Issue by MaHongYan22** [WeBankBlockchain/WeCross#570]
**BUG描述**
Error: code(10000), message(Query to orgPeers:[Peer{ id: 1, name: peer0, channelName: mychannel, url: grpcs://localhost:7051}] endorser failed: Success endorser: 0 Failed endorser: 1["peer: peer0 status: FAILURE message: Channel Channel{id: 4, name: mychannel} Sending proposal with transaction: 89570b8e2bb5b73c0b846e58c46ed1c0f9672db1158ef40146e8a9eef1256f97 to Peer{ id: 1, name: peer0, channelName: mychannel, url: grpcs://localhost:7051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org1MSP], cause=null}", ] payloads:size: 0 [] proposal response consistency: proposalResponses collection is empty)

**重现方式**
重现 BUG 的操作步骤。
例如
按照官网提供脚本搭建fabric1.4接入跨链路由，添加完fabric账户后，在wecross console执行
fabricInstall payment.fabric.sacc Org1 contracts/chaincode/sacc 1.0 GO_LANG 出现报错

**预期结果**
path: classpath:contracts/chaincode/sacc
Result: Success

**环境**
 - 操作系统: Ubuntu20.04.1]
 - 运行库 [ java 11.0.18]
 

**更多信息**
在127.0.0.1-8251-25501的·logs/error.log中的信息
ERROR InterchainJob() - Failed to get interchain requests, path: payment.fabric.WeCrossHub, errorMessage: Query endorser failed: Success endorser: 0 Failed endorser: 2["peer: peer0 status: FAILURE message: Channel Channel{id: 4, name: mychannel} Sending proposal with transaction: 7b750a60ff9231ed5fe96d73f3e1937fb4c9a303b667e00aa8616b90fd11857c to Peer{ id: 1, name: peer0, channelName: mychannel, url: grpcs://localhost:7051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org2MSP], cause=null}", "peer: peer1 status: FAILURE message: Channel Channel{id: 4, name: mychannel} Sending proposal with transaction: 7b750a60ff9231ed5fe96d73f3e1937fb4c9a303b667e00aa8616b90fd11857c to Peer{ id: 2, name: peer1, channelName: mychannel, url: grpcs://localhost:9051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org2MSP], cause=null}", ] payloads:size: 0 [] proposal response consistency: proposalResponses collection is empty
2023-04-13 16:39:27.964 [FabricConnection-20] ERROR Channel() - Channel Channel{id: 4, name: mychannel} Sending proposal with transaction: 3a3cc18bf968f8b1438ea483f557cd17c497a986b7e11cb1818041ece4864847 to Peer{ id: 1, name: peer0, channelName: mychannel, url: grpcs://localhost:7051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org2MSP], cause=null}
java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4469) ~[fabric1-stub-1.3.0.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.webank.wecross.stub.fabric.FabricInnerFunction.sendProposalToPeers(FabricInnerFunction.java:73) ~[fabric1-stub-1.3.0.jar:?]
	at com.webank.wecross.stub.fabric.FabricConnection.queryEndorser(FabricConnection.java:783) ~[fabric1-stub-1.3.0.jar:?]
	at com.webank.wecross.stub.fabric.FabricConnection.call(FabricConnection.java:429) ~[fabric1-stub-1.3.0.jar:?]
	at com.webank.wecross.stub.fabric.FabricConnection.handleCall(FabricConnection.java:226) ~[fabric1-stub-1.3.0.jar:?]
	at com.webank.wecross.stub.fabric.FabricConnection.lambda$handleAsyncCall$1(FabricConnection.java:238) ~[fabric1-stub-1.3.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
	at io.grpc.Status.asRuntimeException(Status.java:530) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[fabric1-stub-1.3.0.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[fabric1-stub-1.3.0.jar:?]
	... 3 more

**Comment by kyonRay** [comment]
感谢提出issue，问题有比较多人提出，我们会尽快给出解决办法。

**Comment by kyonRay** [comment]
请确认fabric链的默认帐号是Org1的

**Comment by MaHongYan22** [comment]
> 请确认fabric链的默认帐号是Org1的
这是我org1和org2两个都试过了忘记调整回设置org1为默认账号了，两个再部署链码saac都失败了
